version: '3.1'
services:
  web:
    build: .
    depends_on:
      - dbpostgresql
    env_file: env/.web_env
    ports:
      - 9090:8080
  dbpostgresql:
    image: postgres:latest
    env_file: env/.data_env
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#volumes:
#  pgdata:
#    external: true